# Generated by Django 4.0.10 on 2023-10-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('performance', models.FloatField()),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
