# Generated by Django 4.0.10 on 2023-10-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='performance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trader',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
